version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
